name: Build Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.12'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate go.sum
      run: go mod tidy

    - name: Check go.sum
      run: if [ ! -f go.sum ]; then touch go.sum; fi

    - name: Build app
      run: chmod +x ./build.sh && ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          ./build/myapp_windows_amd64.exe
          ./build/myapp_linux_amd64
          ./build/myapp_linux_arm64
