name: Build Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.12'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Create go.sum
      run: touch go.sum

    - name: Generate go.sum
      run: go mod tidy

    - name: Check go.sum
      run: if [ ! -f go.sum ]; then touch go.sum; fi

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true

    - name: Build app
      run: chmod +x ./build.sh && ./build.sh

    - name: List build directory
      run: ls -l ./build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 网课构建
        path: |
          ./build/wangke_windows_amd64.exe
          ./build/wangke_linux_amd64
          ./build/wangke_linux_arm64
